### ISSUE TITLE
rejecting a tx in metamask when registering does not re-enable the button

### ISSUE THREAD

**Issue by hayeah** [keymesh/keymesh-dapp#11]
this is after rejecting the tx in metamask

![image](https://user-images.githubusercontent.com/50120/36932784-9c956cb8-1f09-11e8-8341-f9112677a71a.png)

**Comment by ceoimon** [comment]
Are you sure you have rejected the transaction (by clicking "reject" in popup window)? The MetaMask extension icon indicating you have a pending transaction.

**Comment by hayeah** [comment]
solved
