### ISSUE TITLE
landing page

### ISSUE THREAD

**Issue by hayeah** [keymesh/keymesh-dapp#33]
https://www.figma.com/file/IhzFWIxQpxNyO9mUmfH7TArK/KeyMesh?node-id=1325%3A0

![landing page](https://user-images.githubusercontent.com/50120/37249981-172f4ab0-252d-11e8-9ca7-103c24178ab6.jpg)

* Let's do the landing page as a static page, deployed independently on the domain keymesh.io. 
  * Mostly to make the landing page load faster.
----
* [x] mobile friendly
* [x] email collection

**Comment by ceoimon** [comment]
https://github.com/keymesh/keymesh.io

**Comment by dcb9** [comment]
I'll deploy it to AWS CloudFront

**Comment by dcb9** [comment]
https://keymesh.io/

**Comment by ceoimon** [comment]
- [ ] mobile friendly
