### ISSUE TITLE
public key cache busting

### ISSUE THREAD

**Issue by hayeah** [keymesh/keymesh-dapp#46]
if the public key of an addresses changes, how do we refresh the local cache?

maybe check if older than 10 minutes?

**Comment by dcb9** [comment]
we can listen `RegisterOK` event. if the publicKey of local cache appears in the event, we should invalidate the publicKey.

https://github.com/keymesh/trustmesh/blob/d1f6dd235c549d7fbe4b25da2c2991b813fbb3f7/contracts/Identities.sol#L15
